services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_live
    # This line is the magic fix:
    entrypoint: /bin/sh
    command: >
      -c "mkdocs build --clean && python3 -m http.server 8000 --directory site"
    ports:
      - 8000:8000
    volumes:
      - .:/docs
    restart: unless-stopped