site_name: Bytemart Documentation
site_url: https://docs.bytemart.net
theme:
  name: material
  logo: assets/bytemart_logo.png    # The main logo in the header navigation
  favicon: assets/bytemart_logo.png # The tiny icon in the browser tab
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_css:
  - stylesheets/bytemart.css
